# Generated by Django 4.1 on 2022-08-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
